export const AUDIT_ENTITY_INTAKE = "InvoiceIntake";

export const AUDIT_ACTIONS = Object.freeze({
  DEPOSIT_CREATED: "DEPOSIT_CREATED",
  AI_EXTRACTION_COMPLETED: "AI_EXTRACTION_COMPLETED",
  AI_PROCESSING_FAILED: "AI_PROCESSING_FAILED",
  AI_MAX_ATTEMPTS_REACHED: "AI_MAX_ATTEMPTS_REACHED",
  HUMAN_CORRECTION: "HUMAN_CORRECTION",
  HUMAN_VALIDATION: "HUMAN_VALIDATION",
  TRANSACTION_CREATED: "TRANSACTION_CREATED",
  INVOICE_DISCARDED: "INVOICE_DISCARDED",
  POSTED_INVOICE_DELETED: "POSTED_INVOICE_DELETED",
  RECONCILIATION_UPDATED: "RECONCILIATION_UPDATED",
  ACCOUNT_CREATED: "ACCOUNT_CREATED",
  ACCOUNT_UPDATED: "ACCOUNT_UPDATED",
  ACCOUNT_ACTIVATED: "ACCOUNT_ACTIVATED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  EXPENSE_ACCOUNT_DELETED: "EXPENSE_ACCOUNT_DELETED",
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_IMPORTED: "PROJECT_IMPORTED",
  PROJECT_ACTIVATED: "PROJECT_ACTIVATED",
  PROJECT_DEACTIVATED: "PROJECT_DEACTIVATED",
  PROJECT_DELETED: "PROJECT_DELETED",
  STATEMENT_IMPORTED: "STATEMENT_IMPORTED",
  STATEMENT_ADJUSTMENTS_UPDATED: "STATEMENT_ADJUSTMENTS_UPDATED",
  REPORT_ADJUSTMENTS_UPDATED: "REPORT_ADJUSTMENTS_UPDATED",
  POSTED_INVOICE_CORRECTED: "POSTED_INVOICE_CORRECTED",
  RECONCILIATION_AUTO_MATCHED: "RECONCILIATION_AUTO_MATCHED",
  RECONCILIATION_MANUAL_MATCH: "RECONCILIATION_MANUAL_MATCH",
  RECONCILIATION_STATUS_UPDATED: "RECONCILIATION_STATUS_UPDATED",
  RECONCILIATION_DISSOCIATED: "RECONCILIATION_DISSOCIATED",
  RECONCILIATION_EXPORT_GENERATED: "RECONCILIATION_EXPORT_GENERATED",
  CARD_HOLDER_HISTORY_UPDATED: "CARD_HOLDER_HISTORY_UPDATED",
  MERCHANT_ALIAS_UPDATED: "MERCHANT_ALIAS_UPDATED",
  STATEMENT_MATCH_CONFIRMED: "STATEMENT_MATCH_CONFIRMED",
  STATEMENT_MATCH_CHANGED: "STATEMENT_MATCH_CHANGED",
  STATEMENT_MATCH_UNLINKED: "STATEMENT_MATCH_UNLINKED",
  STATEMENT_LINE_IGNORED: "STATEMENT_LINE_IGNORED",
  STATEMENT_MISSING_INVOICE_CONFIRMED: "STATEMENT_MISSING_INVOICE_CONFIRMED",
  STATEMENT_OUTSIDE_RESOLVED: "STATEMENT_OUTSIDE_RESOLVED",
  STATEMENT_IMPORT_REJECTED: "STATEMENT_IMPORT_REJECTED",
  ARCHIVE_PURGE: "ARCHIVE_PURGE",
  USER_CREATED: "USER_CREATED",
  ROLE_ASSIGNED: "ROLE_ASSIGNED",
  INVITATION_SENT: "INVITATION_SENT",
  INVITATION_RESENT: "INVITATION_RESENT",
  INVITATION_FAILED: "INVITATION_FAILED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",
  USER_EMAIL_UPDATED: "USER_EMAIL_UPDATED",
  USER_ACTIVATED: "USER_ACTIVATED",
});

export function auditEventId(receiptId, action, suffix = "") {
  const safeReceiptId = String(receiptId).replace(/[^a-zA-Z0-9_-]/g, "-");
  const safeAction = String(action).replace(/[^a-zA-Z0-9_-]/g, "-");
  const safeSuffix = suffix ? `-${String(suffix).replace(/[^a-zA-Z0-9_-]/g, "-")}` : "";
  return `AUDIT-${safeReceiptId}-${safeAction}${safeSuffix}`.slice(0, 128);
}

export function auditDetails(value) {
  return JSON.stringify(value ?? {});
}

export function parseAuditDetails(value) {
  if (!value) return {};
  try {
    const parsed = JSON.parse(value);
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    return { message: value };
  }
}
