export const AUDIT_ENTITY_INTAKE = "InvoiceIntake";

export const AUDIT_ACTIONS = Object.freeze({
  DEPOSIT_CREATED: "DEPOSIT_CREATED",
  AI_EXTRACTION_COMPLETED: "AI_EXTRACTION_COMPLETED",
  AI_PROCESSING_FAILED: "AI_PROCESSING_FAILED",
  HUMAN_CORRECTION: "HUMAN_CORRECTION",
  HUMAN_VALIDATION: "HUMAN_VALIDATION",
  TRANSACTION_CREATED: "TRANSACTION_CREATED",
  RECONCILIATION_UPDATED: "RECONCILIATION_UPDATED",
  ACCOUNT_CREATED: "ACCOUNT_CREATED",
  ACCOUNT_UPDATED: "ACCOUNT_UPDATED",
  ACCOUNT_ACTIVATED: "ACCOUNT_ACTIVATED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  EXPENSE_ACCOUNT_DELETED: "EXPENSE_ACCOUNT_DELETED",
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_IMPORTED: "PROJECT_IMPORTED",
  PROJECT_ACTIVATED: "PROJECT_ACTIVATED",
  PROJECT_DEACTIVATED: "PROJECT_DEACTIVATED",
  PROJECT_DELETED: "PROJECT_DELETED",
  STATEMENT_IMPORTED: "STATEMENT_IMPORTED",
  RECONCILIATION_AUTO_MATCHED: "RECONCILIATION_AUTO_MATCHED",
  RECONCILIATION_MANUAL_MATCH: "RECONCILIATION_MANUAL_MATCH",
  RECONCILIATION_STATUS_UPDATED: "RECONCILIATION_STATUS_UPDATED",
  RECONCILIATION_DISSOCIATED: "RECONCILIATION_DISSOCIATED",
  RECONCILIATION_EXPORT_GENERATED: "RECONCILIATION_EXPORT_GENERATED",
});

export function auditEventId(receiptId, action, suffix = "") {
  const safeReceiptId = String(receiptId).replace(/[^a-zA-Z0-9_-]/g, "-");
  const safeAction = String(action).replace(/[^a-zA-Z0-9_-]/g, "-");
  const safeSuffix = suffix ? `-${String(suffix).replace(/[^a-zA-Z0-9_-]/g, "-")}` : "";
  return `AUDIT-${safeReceiptId}-${safeAction}${safeSuffix}`.slice(0, 128);
}

export function auditDetails(value) {
  return JSON.stringify(value ?? {});
}

export function parseAuditDetails(value) {
  if (!value) return {};
  try {
    const parsed = JSON.parse(value);
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    return { message: value };
  }
}
